CREATE TABLE payments (
npi                             varchar(10),    --"National Provider Identifier"       
nppes_provider_last_org_name    varchar(70),    --"Last Name/Organization Name of the Provider"
nppes_provider_first_name 	varchar(20),    --"First Name of the Provider"
nppes_provider_mi		character(1),	--"Middle Initial of the Provider"
nppes_credentials 		varchar(20),	--"Credentials of the Provider"
nppes_provider_gender 		character(1),	--"Gender of the Provider"
nppes_entity_code 		character(1),	--"Entity Type of the Provider"
nppes_provider_street1 		varchar(55),	--"Street Address 1 of the Provider"
nppes_provider_street2 		varchar(55),    --"Street Address 2 of the Provider"
nppes_provider_city 		varchar(40),	--"City of the Provider"
nppes_provider_zip 		varchar(20),	--"Zip Code of the Provider"
nppes_provider_state 		character(2),	--"State Code of the Provider"
nppes_provider_country 		character(2),	--"Country Code of the Provider"
provider_type	 		varchar(43),	--"Provider Type of the Provider"
medicare_participation_indicator character(1), 	--"Medicare Participation Indicator"
place_of_service 		character(1),	--"Place of Service"
hcpcs_code       		varchar(5),	--"HCPCS Code"
hcpcs_description 		varchar(256),	--"HCPCS Description"
hcpcs_drug_indicator		character(1),	--"Identifies HCPCS As Drug Included in the ASP Drug List"
line_srvc_cnt    		numeric(11,2),	--"Number of Services"
bene_unique_cnt  		numeric(11,2),	--"Number of Medicare Beneficiaries"
bene_day_srvc_cnt 		numeric(11,2),	--"Number of Distinct Medicare Beneficiary/Per Day Services"
average_Medicare_allowed_amt 	numeric(11,2),	--"Average Medicare Allowed Amount"
average_submitted_chrg_amt 	numeric(11,2),	--"Average Submitted Charge Amount"
average_Medicare_payment_amt 	numeric(11,2),	--"Average Medicare Payment Amount"
average_Medicare_standard_amt	numeric(11,2)	--"Average Medicare Standardized Payment Amount";
);
